/*
 *  Created on: 28/ott/2014
 *      Author: Cristian
 */

#ifndef IMUVECPP_H_
#define IMUVECPP_H_


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT jfloat JNICALL Java_com_imuve_cristian_imuve_MainActivity_GetVersion (JNIEnv *jenv, jobject jobj);
JNIEXPORT jint JNICALL Java_com_imuve_cristian_imuve_MainActivity_LoadDwg (JNIEnv *jenv, jobject jobj, jbyteArray pData, jint pDataSize, jint Options);
JNIEXPORT jint JNICALL Java_com_imuve_cristian_imuve_MainActivity_GetDwgID(JNIEnv *jenv, jobject jobj, jint Options);
JNIEXPORT jstring JNICALL Java_com_imuve_cristian_imuve_MainActivity_GetError(JNIEnv *jenv, jobject jobj);

JNIEXPORT jint JNICALL Java_com_imuve_cristian_imuve_MainActivity_DrawDwg (JNIEnv *jenv, jobject jobj, jint pDacurTabta, jint drawOptions);


JNIEXPORT jint JNICALL Java_com_imuve_cristian_imuve_MainActivity_Pan (JNIEnv *jenv, jobject jobj, jfloat dx, jfloat dy, jint isTransacting);
JNIEXPORT jint JNICALL Java_com_imuve_cristian_imuve_MainActivity_Zoom (JNIEnv *jenv, jobject jobj, jfloat x, jfloat y, jfloat zoomm, jint isTransacting);

JNIEXPORT jstring JNICALL Java_com_imuve_cristian_imuve_MainActivity_DwgToCanvas(JNIEnv *jenv, jobject jobj, jint width, jint height, jint Options);
JNIEXPORT jstring JNICALL Java_com_imuve_cristian_imuve_MainActivity_DwgToCanvasEx(JNIEnv *jenv, jobject jobj, jint width, jint height, 
															jstring fileName, jint maxEntities,
															jint geoRefMethod,
															jdouble Long, jdouble Lat, jdouble Long2, jdouble Lat2,
															jint Options);

JNIEXPORT jstring JNICALL Java_com_imuve_cristian_imuve_MainActivity_DwgToJSON(JNIEnv *jenv, jobject jobj, jint Aux, jint Options);


JNIEXPORT jint JNICALL Java_com_imuve_cristian_imuve_MainActivity_FindDwgText(JNIEnv *jenv, jobject jobj, jstring jstrSearch, jint Options);
JNIEXPORT jstring JNICALL Java_com_imuve_cristian_imuve_MainActivity_WrapText(JNIEnv *jenv, jobject jobj, jstring jText, jint Mode);


JNIEXPORT jfloat JNICALL Java_com_imuve_cristian_imuve_MainActivity_GetCamera(JNIEnv *jenv, jobject jobj, jint Options);
JNIEXPORT jint JNICALL Java_com_imuve_cristian_imuve_MainActivity_SetCamera(JNIEnv *jenv, jobject jobj, jfloat CameraX, jfloat CameraY, jfloat CameraWX, jfloat CameraWY);
JNIEXPORT jint JNICALL Java_com_imuve_cristian_imuve_MainActivity_SetScreen(JNIEnv *jenv, jobject jobj, jfloat ScreenWX, jfloat ScreenWY);

JNIEXPORT jint JNICALL Java_com_imuve_cristian_imuve_MainActivity_SetLayer(JNIEnv *jenv, jobject jobj, jstring layer_name, jboolean isON);
JNIEXPORT jint JNICALL Java_com_imuve_cristian_imuve_MainActivity_GetLayers(JNIEnv *jenv, jobject jobj);


#ifdef __cplusplus
}
#endif


#endif /* IMUVECPP_H_ */
